### ISSUE TITLE
Online model doesn't work

### ISSUE THREAD

**Issue by Jiaqi-Chen-00** [eduardzamfir/seemoredetails#10]
![图片](https://github.com/user-attachments/assets/77a8a95c-ff65-44cc-b482-e761d32c05e7)
Why dosen't it work at all?

**Comment by eduardzamfir** [comment]
Hi,
this model was trained for bicubic degradations only, if your input image contains unknown degradations, the model won't work as expected. In case you're interested in real-world SR, you can retrain the network using a complex degradation pipeline, such as Real-ESRGAN or BSRGAN.

Have fun!
