### ISSUE TITLE
About pretrain model

### ISSUE THREAD

**Issue by ReBenDish** [eduardzamfir/seemoredetails#11]
Hi！This is a great work, but I would like to know if you would mind making the training model of SeemoRe_L public so that it is easier to test.

**Comment by eduardzamfir** [comment]
hey,  I uploaded the B size model checkpoints, the larger size checkpoints I have to re-train first.

**Comment by ReBenDish** [comment]
Thanks for your reply！I think that in addition to proposing an efficient T model, the powerful but fast T is also a very outstanding work in the article.

**Comment by eduardzamfir** [comment]
I uploaded the retrained checkpoints for SeemoRe_L, thanks for your patience.
