### ISSUE TITLE
python package for SeemoRe

### ISSUE THREAD

**Issue by Sanster** [eduardzamfir/seemoredetails#12]
Thank you for the open-source model. I packaged your model into a Python package for easier use (the model will download automatically). Looking forward to the release of large models.

https://github.com/Sanster/seemore

```bash
pip install seemore
```

```python
from seemore import SeemoReUpscaler
import cv2

# Initialize the upscaler
upscaler = SeemoReUpscaler("seemore_b_x4", device="cpu")

# Load and upscale an image
image = cv2.imread("input.jpg")
result = upscaler(image)
```

**Comment by eduardzamfir** [comment]
hi,

cool, thanks! I uploaded now all checkpoints for the larger model as well. Sorry for the delay
