### ISSUE TITLE
About LayerNorm (layer normalization)

### ISSUE THREAD

**Issue by seanko29** [eduardzamfir/seemoredetails#13]
Hello!

First of all, thank you for the awesome work :). It helps in studying SR. 

I just want to ask about layer normalization position (before or after the MoRe,SEE or GatedFFN) block.
Are there any particular reasons that the LayerNorm came before every feature extraction blocks? or are they obtained heuristically?

Thank you in advanced!

**Comment by eduardzamfir** [comment]
Hey,

Thanks for your interest.

we follow the standard transformer-like block design which uses a pre-norm. However, I didn’t experiment with different layer norm positions, only if we remove it, the psnr/ssim can decrease. You might have a look into post-norm, or removing it entirely.
