### ISSUE TITLE
Please consider adding a license

### ISSUE THREAD

**Issue by RunDevelopment** [eduardzamfir/seemoredetails#6]
Hello! 

Could please consider adding a license to SeemoRe? This would allow the community to adopt SeemoRe, more easily train custom models, and then distribute programs supporting SeemoRe PyTorch models. In particular, I would like to add SeemoRe to [spandrel](https://github.com/chaiNNer-org/spandrel), a free and open-source library for loading and running SR models (and similar).

**Comment by eduardzamfir** [comment]
Hey,

Thanks for your interest in our work. We added a license to our repository.

Best,
Eduard

**Comment by RunDevelopment** [comment]
Thank you!
