### ISSUE TITLE
Counting number of params and macs

### ISSUE THREAD

**Issue by seanko29** [eduardzamfir/seemoredetails#7]
Hello, 

Your work looks great. Thank you for posting your code as well.

I have a question regarding number of params and macs in the paper. 

did you use the fvcore library to count the number of params and flops (and maybe divide by 2 to find for number of MACs)?
   from fvcore.nn import flop_count_table, FlopCountAnalysis, ActivationCountAnalysis

If not, may I know how did you get your numbers in the table. 

Thank you in advanced :).

**Comment by eduardzamfir** [comment]
Hi, thank you for your interest in our work. 
Yes, we used the fvcore for counting params and MACs and double checked with the numbers presented by SRFormer, SAFMN and DAT. Did you experience any inconsistencies?

**Comment by seanko29** [comment]
@eduardzamfir Hello!
I fixed the problem. 
I forgot to divide height and width by the scaling factor (x2, x3 , x4) when we measure flops.
Prolbem solved. Thanks ! 
Just wondering why other papers mention FLOPs and you mentioned MACs in the table? 
From  what I know, 1 MACS = 2FLOPs.

**Comment by eduardzamfir** [comment]
Ok, good to here. We followed SRFormer which reports MACs, however it seems as if FLOPs would be better.
