### ISSUE TITLE
Release for the B and L models

### ISSUE THREAD

**Issue by distoramos** [eduardzamfir/seemoredetails#8]
Dear Developer,
I had the chance to test your super resolution work for 2x and T models and I am impressed by the results.
Any plans to share the B and L models in the future.

Regards,

**Comment by eduardzamfir** [comment]
Hey! 

Thanks so much for your interest. I’ll be uploading the larger models by September, so feel free to ping me if I forget to post the checkpoints :)

**Comment by dongdk** [comment]
any update?
