### ISSUE TITLE
Asking a script to infer 

### ISSUE THREAD

**Issue by WeijianZhang123** [eduardzamfir/seemoredetails#9]
Hello, thanks for your amazing work!

Could you please add an _**inter.py**_ script that can infer custom images?
Looking forward to your reply!

**Comment by eduardzamfir** [comment]
hi, thanks for your interest.

Please checkout our hugging face [demo](https://huggingface.co/spaces/eduardzamfir/SeeMoreDetails).

Best,
Eduard

**Comment by dongdk** [comment]
hi @eduardzamfir can u add it to this repo? thanks

**Comment by eduardzamfir** [comment]
https://huggingface.co/spaces/eduardzamfir/SeeMoreDetails/blob/main/app.py
